<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mission_recorder</name>
  <version>0.1.0</version>
  <description>Mission recording, mission files and export.</description>
  <maintainer email="node@example.org">NODE Engineering Club</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>asket_interfaces</depend>
  <depend>asket_common</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>diagnostic_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
